### ISSUE TITLE
BE: Rust and ELFv2 on glibc

### ISSUE THREAD

**Issue by q66** [void-ppc64/void-packages#12]
Right now, Rust is not being handled for ELFv2 on glibc; while LLVM is patched appropriately, Rust is not, and it still requires some ELFv2 specific bits in its source code (particularly `librustc_target`).

The main problem here is that Rust has no `-mabi` switch, and if we patch Rust to use ELFv2 always, it won't be possible to use it for interoperability with legacy systems, and such changes also won't be accepted upstream.

My current proposed solution is to add a new target triple for Void (say, `powerpc64-void-linux-gnu`) and force `rustc` to emit ELFv2 when compiling for that but not for `powerpc64-*-linux-gnu`. Then we can alter the build/cross-profiles to use the new triple, which means behavior for `powerpc64-*-linux-gnu` will remain unchanged.

@pullmoll, what do you think?

**Comment by q66** [comment]
A potential problem with this is e.g. `firefox` which uses the generic `XBPS_TRIPLET` and is not aware of the rust triplet.

**Comment by pullmoll** [comment]
I don't have too much experience with rust, if any. What I know is that it takes ages to build :)
The workaround you described solves the issue for Void we should patch it to get packages depending on rust built with the elfv2 ABI.

At the same time we could perhaps ask upstream if they are willing implement a `-mabi=elfv{1,2}` switch. The pro argument is that various compilers (which?) already support it and perhaps we (you?) can even create a not too invasive patch for rust they can accept.

In any case I'm available for testing results on the G5.

**Comment by q66** [comment]
Well, adding the switch to `rustc` would not help that much as the rest of the build infra wouldn't know how to work with it... so I think a triplet is our best bet for now...

**Comment by q66** [comment]
I dug around in the internals, seems like Rust never requests an ABI from LLVM in the first place, relying on the triple defaults. There doesn't seem to be a trivial way to patch it in either. I guess our best bet is to patch Rust for the time being and forget about supporting the old ABI.

In longer run it might be worth it to introduce a new triple for the whole system, something like `powerpc64-(unknown-)-linux-gnuelfv2` and use it for *all* the tooling. That's going to be a significant amount of effort that will need more preparation though.

**Comment by q66** [comment]
```
bash-5.0# echo 'fn main() { println!("hello world"); }' > test.rs
bash-5.0# rustc test.rs
bash-5.0# ./test
hello world
bash-5.0# rustc --version
rustc 1.34.0
bash-5.0# uname -a
Linux bevoid 5.0.9_1 #1 SMP Mon Apr 29 11:43:43 UTC 2019 ppc64 GNU/Linux
```
