### ISSUE TITLE
BE ppc64: Kernel 4.19.37 and 5.0.10 lockup after some minutes

### ISSUE THREAD

**Issue by pullmoll** [void-ppc64/void-packages#14]
Both kernels hang after some minutes triggering the watchdog, resulting in a panic.
Here's a screenshot since I'm not sure I can find that info after a reboot:

![g5-watchdog](https://user-images.githubusercontent.com/10061347/57017662-5dcd4e00-6c20-11e9-8a1b-d83906a97491.png)

5.0.10 saw several fixes in the timer code so this is probably related.
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.19.37
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.0.10

**Comment by q66** [comment]
Hm, 5.0.10 works on the Talos 2, without any lockups. This would be best brought up upstream...

**Comment by pullmoll** [comment]
Hmm, now 5.0.10 ran for several hours so it's not as reproducible as I thought.
I'll try to find out more before reporting on the kernel bugzilla.

**Comment by pullmoll** [comment]
Great! Now my G5 is dead. It does no longer play the chime when I power up and does not display anything. Only thing it seems to do is some accesses to the HDD. Then it freezes and the windpark begins to run all fans at full speed.

I either broke it by my experiments or something has happened to openfirmware. No testing anymore until I can fix this box, if at all.

**Comment by q66** [comment]
If you have the liquid cooling version, you should check for liquid leakage, it's a classic issue with those...

**Comment by pullmoll** [comment]
No, it's a Power Mac G5 Dual (Late 2005), i.e. a 2 CPU model with cooling fans, no liquid cooling.
http://lowendmac.com/2005/power-mac-g5-dual/
I'll see what it does without HDD and try some more things.

**Comment by pullmoll** [comment]
Fortunately my 2nd Power Mac, the one with the damaged case, still works fine and it does not freeze. I think the reported problem was just because my machine was about to die and not due to a bug, thus closing this.

**Comment by q66** [comment]
Alright. Maybe you can swap the logic board between the two cases?

**Comment by pullmoll** [comment]
That's probably a lot of work. The case is ugly but then who cares? It's always opened anyway :)

**Comment by pullmoll** [comment]
One thing left to try the other day I saw somewhere on ifixit.com. There is an on-board micro switch to reset the PRAM if held for 30 seconds while powering up.
