### ISSUE TITLE
musl: broken linkage with ld.gold/possibly miscompiled gcc

### ISSUE THREAD

**Issue by q66** [void-ppc64/void-packages#15]
When attempting to link things with `ld.gold`:

```
[q66@/home/q66/void-packages/masterdir-musl /]$ echo "int main(){}" > test.c
[q66@/home/q66/void-packages/masterdir-musl /]$ gcc test.c -o test
[q66@/home/q66/void-packages/masterdir-musl /]$ gcc test.c -o test -fuse-ld=gold
/usr/bin/ld.gold: error: /usr/lib/gcc/powerpc64le-linux-musl/8.3.0/../../../../lib/libc.so uses 64-bit long double, /usr/lib/gcc/powerpc64le-linux-musl/8.3.0/../../../../lib/libgcc_s.so.1 uses 128-bit long double
collect2: error: ld returned 1 exit status
```

This breaks compilation of e.g. `webkit2gtk` besides possibly other things. From the error message, it would seem that `libgcc_s.so.1` for whatever reason uses 128-bit `long double`, even though we explicitly patch gcc to force 64-bit `long double` on `musl` as the libc needs (`0010-ldbl128-config.patch`) as well as use `-mlong-double-64` in default `CFLAGS`/`CXXFLAGS` for musl. So I kinda have no idea what's going on.

@pullmoll if you have a `ppc64-musl` BE chroot/masterdir on your G5, could you test that (i only have a glibc BE system available right now)? Or maybe got any idea what might be happening here?

**Comment by q66** [comment]
Yeah, I just set up a simple chroot on the BE machine and got the same

```
bash-5.0# gcc test.c -o test -fuse-ld=gold
/usr/bin/ld.gold: error: /usr/lib/gcc/powerpc64-linux-musl/8.3.0/../../../../lib/libc.so uses 64-bit long double, /usr/lib/gcc/powerpc64-linux-musl/8.3.0/../../../../lib/libgcc_s.so.1 uses 128-bit long double
collect2: error: ld returned 1 exit status
```

**Comment by pullmoll** [comment]
Hm, `cross-powerpc64-linux-musl/template` does not set any `C{,XX}FLAGS` besides `-Os -pipe -fPIC` so perhaps we would have to add `-mlong-double=64` here.
Or is the `0010-ldbl128-config.patch` supposed to make this option be inserted into the gcc bootstrap and/or final stages? Inspecting the log of building `cross-powerpc-linux-musl` should tell.

**Comment by q66** [comment]
Further inspection reveals the following:

```
$ readelf -a libgcc_s.so.1|grep ABI_FP
  Tag_GNU_Power_ABI_FP: hard float, 128-bit IBM long double
```

Every other shared library in the system that uses `long double` seems to correctly use 64-bit.

Compiler defaults also seem fine:

```
[q66@/home/q66/void-packages/masterdir-musl /]$ echo "int foo(long double v){ return (int)v; }" > lib.c
[q66@/home/q66/void-packages/masterdir-musl /]$ gcc lib.c -shared -o lib.so -mlong-double-64
[q66@/home/q66/void-packages/masterdir-musl /]$ readelf -a lib.so|grep FP
  Tag_GNU_Power_ABI_FP: hard float, 64-bit long double
[q66@/home/q66/void-packages/masterdir-musl /]$ gcc lib.c -shared -o lib.so -mlong-double-128
[q66@/home/q66/void-packages/masterdir-musl /]$ readelf -a lib.so|grep FP
  Tag_GNU_Power_ABI_FP: hard float, 128-bit IBM long double
[q66@/home/q66/void-packages/masterdir-musl /]$ gcc lib.c -shared -o lib.so
[q66@/home/q66/void-packages/masterdir-musl /]$ readelf -a lib.so|grep FP
  Tag_GNU_Power_ABI_FP: hard float, 64-bit long double
```

Additionally, Adélie Linux seems to have the exact same problem, just confirmed with the maintainer, though they don't get to see the error because they don't ship `ld.gold` and `ld.bfd` does not check it. Their system seems to be running fine otherwise so it would seem it doesn't cause issues in practice (other than the `ld.gold` linkage problems) so the severity might not be great but it should possibly be fixed anyway...

**Comment by q66** [comment]
This is the most likely cause: https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/rs6000/t-linux

**Comment by q66** [comment]
I came up with a patch https://gist.github.com/q66/516597503675e0b36147b8c182e80b3d

it seems to work, managed to compile webkit and link it with gold and stuff

i'll build more software with it, and then PR it into void...

**Comment by q66** [comment]
https://github.com/void-linux/void-packages/pull/11466
