### ISSUE TITLE
x265: illegal instruction on ppc64 (BE)

### ISSUE THREAD

**Issue by pullmoll** [void-ppc64/void-packages#16]
Trying to run mpv on ppc64 results in a signal 11 (TRAP) when trying to execute an illegal instruction. According to `gdb` the source is `_GLOBAL__sub_I_intrapred_altivec.cpp(void) ()` at `intrapred_altivec.cpp` line 30808 but that's just the last line of that file.

The invalid assembler code at above function's address `+<96>` is `stxvw4x vs32,0,r9`.
Is this perhaps a power8 or power9 only instruction?

**Comment by q66** [comment]
Yeah, looks like power8.

**Comment by q66** [comment]
Try adding `-DCPU_POWER8=OFF` in x265 build and report back

**Comment by pullmoll** [comment]
I saw it is [a deprectated instruction](http://openpowerfoundation.org/wp-content/uploads/resources/leabi/content/dbdoclet.50655244_90667.html).

**Comment by q66** [comment]
When on POWER, x265 will by default enable POWER8 build and pass `mcpu=power8`, which will let the compiler emit POWER8 instructions: https://github.com/videolan/x265/blob/master/source/CMakeLists.txt#L464

so you need to disable the option as i stated above. I think disabling altivec entirely (`-DENABLE_ALTIVEC=OFF`) should not be necessary though

**Comment by pullmoll** [comment]
Sadly x265 does not build with `-DCPU_POWER8=OFF`.

**Comment by q66** [comment]
any error logs?

**Comment by q66** [comment]
Okay. Looks like we'll have to disable altivec entirely for BE then, Debian seems to be doing the same. So pass these two flags for now...

**Comment by pullmoll** [comment]
Here's [the build log](https://gist.github.com/pullmoll/8d63a9d5946317cc61b515cff97250ad#file-x265-build-errors-ppc64-txt).
I'll try with disabling altivec altogether. This will make x265 mostly unusable on ppc64 :P

**Comment by q66** [comment]
Well, I checked and it seems all the altivec stuff is written against POWER8+. So not much we can do... those who want to run BE and have POWER8+ will have to build their own x265...

**Comment by q66** [comment]
don't push it, please, i'll come up with a proper fix that makes altivec into an option (so people can enable it)

**Comment by q66** [comment]
oh, you already did... well, nevermind then, i'll do it properly anyway

**Comment by pullmoll** [comment]
We can always push a better solution later on. I wanted to continue testing packages on ppc64 and x265 is used by quite some applications.

**Comment by q66** [comment]
Looks like our x265 template was broken in some ways otherwise anyway (even on x86 and other archs). So I'm fixing it for all :)
