### ISSUE TITLE
BE: glibc ELFv2

### ISSUE THREAD

**Issue by q66** [void-ppc64/void-packages#5]
This is WIP by @pullmoll and seems to be nearly ready for upstreaming.

**Comment by pullmoll** [comment]
I pushed a new branch ppc64-gnu containing (most of) my branch off void-linux/void-packages
I have not yet tried if it works while I intend to re-bootstrap x86_64 and build ppc64 from this fork of void-packages.

**Comment by q66** [comment]
Looks good, I'm currently in Vienna for EH19 but returning home tomorrow, so i'll rebase master+staging against current void-linuxvoid-packages/, so that the branch can also be rebased; then i'll do some testing on it, and if it works i think we can upstream those changes at least, commits look nice and clean

**Comment by q66** [comment]
Currently picking the initial commits into `staging` and building the crosstoolchain. I altered your commit to allow building the crosstoolchain on `ppc64le` hosts as well, so that I can compile to it, so testing that now.

**Comment by q66** [comment]
I noticed some broken bits in  the crosstoolchain template (glibc headers was setting --target but not --host, which broke target detection). So I just amended the commit with the fix, and I have a working toolchain now, and was able to compile bash.

**Comment by q66** [comment]
https://github.com/void-linux/void-packages/pull/11352 Any further issues will be introduced as new tickets
